### PR TITLE
refactor(tofs): update with latest changes inc. 100% portable `libtofs.jinja`

### PR DESCRIPTION
**Pull request by myii**
This PR covers three things.

#### (A) refactor(tofs): avoid using “salt['config.get']” for formula writers

Introduce all code improvements from https://github.com/saltstack-formulas/template-formula/pull/77.

#### (B) refactor(tofs): move `files_switch` macro to `libtofs.jinja`

As suggested by @alxwr in [this comment](https://github.com/saltstack-formulas/template-formula/pull/77#issuecomment-474254044) on the PR linked above.

#### (C) refactor(tofs): make `files_switch` macro fully portable

Introduce `v1_path_prefix` parameter to resolve the problem mentioned by @baby-gnu in [this comment](https://github.com/saltstack-formulas/template-formula/pull/77#issuecomment-474266337) on the PR linked above.

---

Improvements and test results will be added to subsequent comments.

### CODE REVIEW

**Comment by myii** [comment]
The implementation for part (C) has actually resulted in an improvement to the `source` lists generated.  Based on the following test pillar:

```yaml
systemd:
  tofs:
    files_switch:
      - any/path/can/be/used/here
      - id
      - osfinger
      - os
      - os_family
    dirs:
      files: files_alt
      default: default_alt
    source_files:
      networkd:
        - 'network_alt'
      resolved:
        - 'resolved_alt.conf'
      timesyncd:
        - 'timesyncd_alt.conf'
```

The diff before and after (C):

```diff
--- Before (C)
+++ After (C)
@@ -11,18 +11,6 @@
       - salt://systemd/networkd/files_alt/Ubuntu/network_alt
       - salt://systemd/networkd/files_alt/Debian/network_alt
       - salt://systemd/networkd/files_alt/default_alt/network_alt
-      - salt://systemd/resolved/files_alt/any/path/can/be/used/here/network_alt
-      - salt://systemd/resolved/files_alt/ABC/network_alt
-      - salt://systemd/resolved/files_alt/Ubuntu-16.04/network_alt
-      - salt://systemd/resolved/files_alt/Ubuntu/network_alt
-      - salt://systemd/resolved/files_alt/Debian/network_alt
-      - salt://systemd/resolved/files_alt/default_alt/network_alt
-      - salt://systemd/timesyncd/files_alt/any/path/can/be/used/here/network_alt
-      - salt://systemd/timesyncd/files_alt/ABC/network_alt
-      - salt://systemd/timesyncd/files_alt/Ubuntu-16.04/network_alt
-      - salt://systemd/timesyncd/files_alt/Ubuntu/network_alt
-      - salt://systemd/timesyncd/files_alt/Debian/network_alt
-      - salt://systemd/timesyncd/files_alt/default_alt/network_alt
 
     - source:
       - salt://systemd/files_alt/any/path/can/be/used/here/resolved_alt.conf
@@ -31,24 +19,12 @@
       - salt://systemd/files_alt/Ubuntu/resolved_alt.conf
       - salt://systemd/files_alt/Debian/resolved_alt.conf
       - salt://systemd/files_alt/default_alt/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/any/path/can/be/used/here/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/ABC/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/Ubuntu-16.04/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/Ubuntu/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/Debian/resolved_alt.conf
-      - salt://systemd/networkd/files_alt/default_alt/resolved_alt.conf
       - salt://systemd/resolved/files_alt/any/path/can/be/used/here/resolved_alt.conf
       - salt://systemd/resolved/files_alt/ABC/resolved_alt.conf
       - salt://systemd/resolved/files_alt/Ubuntu-16.04/resolved_alt.conf
       - salt://systemd/resolved/files_alt/Ubuntu/resolved_alt.conf
       - salt://systemd/resolved/files_alt/Debian/resolved_alt.conf
       - salt://systemd/resolved/files_alt/default_alt/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/any/path/can/be/used/here/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/ABC/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/Ubuntu-16.04/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/Ubuntu/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/Debian/resolved_alt.conf
-      - salt://systemd/timesyncd/files_alt/default_alt/resolved_alt.conf
 
     - source:
       - salt://systemd/files_alt/any/path/can/be/used/here/timesyncd_alt.conf
@@ -57,18 +33,6 @@
       - salt://systemd/files_alt/Ubuntu/timesyncd_alt.conf
       - salt://systemd/files_alt/Debian/timesyncd_alt.conf
       - salt://systemd/files_alt/default_alt/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/any/path/can/be/used/here/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/ABC/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/Ubuntu-16.04/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/Ubuntu/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/Debian/timesyncd_alt.conf
-      - salt://systemd/networkd/files_alt/default_alt/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/any/path/can/be/used/here/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/ABC/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/Ubuntu-16.04/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/Ubuntu/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/Debian/timesyncd_alt.conf
-      - salt://systemd/resolved/files_alt/default_alt/timesyncd_alt.conf
       - salt://systemd/timesyncd/files_alt/any/path/can/be/used/here/timesyncd_alt.conf
       - salt://systemd/timesyncd/files_alt/ABC/timesyncd_alt.conf
       - salt://systemd/timesyncd/files_alt/Ubuntu-16.04/timesyncd_alt.conf
```

* Basically, all of the unnecessary sources that were being constructed by the `for` loop have now been removed.

**Comment by myii** [comment]
@baby-gnu Let me push the last couple of commits I was working on.  That solves this problem.

**Comment by myii** [comment]
@aboe76 Thanks for the review, appreciate it.

**Comment by aboe76** [comment]
@myii merged it

**Comment by myii** [comment]
@aboe76 Thanks.

**Comment by alxwr** [comment]
I never thought that `libtofs.jinja` would become a reality so quick. :eyes: 
Thank you @myii, @baby-gnu and @aboe76 (and whomever I've forgotten)!

**Comment by myii** [comment]
@alxwr Thanks for the idea, it was a good one!  With something like TOFS, it's easiest to work on it while it's still relatively fresh in your mind.  Want to get it to the point where that macro is "finished", so that we can start deploying without having to worry about it any more.  This idea led to what I believe is the final solution and 100% portability.  My assertion is that this is ready to be used everywhere, once we place it into `template-formula`.  That shouldn't take too long now.

**Comment by alxwr** [comment]
@myii I'm looking forward to `libtofs.jinja` being stable. :-)
Hopefully my limited time allows me to use it in some formulas (and my own setup).

**Pull request merged**
