### PR TITLE
feat(centos-stream): add Centos Stream support

### PR DESCRIPTION
**Pull request by aboe76**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

missing centos stream support

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by aboe76** [comment]
@myii nice find, couldn't find one on dockerhub..

**Comment by myii** [comment]
@aboe76 I feel like I've come across this before (`Event loop failed: Connection timed out`) but I can't recall the resolution.  Do you know what the right step is?

```console
[root@cd362408ceb6 ~]# journalctl -xeu systemd-networkd-wait-online.service
-- Logs begin at Thu 2021-10-07 21:17:07 UTC, end at Thu 2021-10-07 21:33:38 UTC. --
Oct 07 21:17:39 cd362408ceb6 systemd[1]: Starting Wait for Network to be Configured...
-- Subject: Unit systemd-networkd-wait-online.service has begun start-up
-- Defined-By: systemd 
-- Support: https://access.redhat.com/support
--
-- Unit systemd-networkd-wait-online.service has begun starting up.
Oct 07 21:19:39 cd362408ceb6 systemd-networkd-wait-online[411]: Event loop failed: Connection timed out
Oct 07 21:19:39 cd362408ceb6 systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Oct 07 21:19:39 cd362408ceb6 systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd 
-- Support: https://access.redhat.com/support
--
-- The unit systemd-networkd-wait-online.service has entered the 'failed' state with result 'exit-code'.
Oct 07 21:19:39 cd362408ceb6 systemd[1]: Failed to start Wait for Network to be Configured.
-- Subject: Unit systemd-networkd-wait-online.service has failed
-- Defined-By: systemd 
-- Support: https://access.redhat.com/support
--
-- Unit systemd-networkd-wait-online.service has failed.
--
-- The result is failed.
```

**Comment by aboe76** [comment]
I think because its before the network state, it's already running so the
network state is already online.

Op do 7 okt. 2021 23:41 schreef Imran Iqbal ***@***.***>:

**Comment by myii** [comment]
> @myii I was thinking about the 'systemd-wait-online' stuff, and I think it should only be enabled not running. because it's meant because it's a oneshot service

@aboe76 That makes sense.  I just tried it by modifying this block:

https://github.com/saltstack-formulas/systemd-formula/blob/56520008175491d3a5deecc2b5fa02c6834944f3/systemd/networkd/init.sls#L34-L37

To:

```sls
wait_online:
  service.enabled:
    - name: systemd-networkd-wait-online
```

And the `kitchen test` works fine on CentOS Stream 8.  Would you like to propose that in a PR?  I reckon we'll be able to enable more of the commented instances in the CI after this change.

**Comment by myii** [comment]
@aboe76 Does it work OK in your CentOS Stream 8 VM?  If so, how about we resolve this another way?  We could just modify how the state runs in Kitchen only, in a similar way to how we did it in these two PRs:

* https://github.com/saltstack-formulas/rng-tools-formula/pull/5
* https://github.com/saltstack-formulas/ntp-formula/pull/47

That way we're not changing the formula itself but at least we're running the CI for the platforms where only this one state is failing.

**Comment by aboe76** [comment]
@myii Yes I think that's better, because systemd-networkd-wait-online works without issues

**Comment by myii** [comment]
@aboe76 OK, as an initial test, running with `networkd.wait_online: false` on all `master` instances:

* https://gitlab.com/myii/systemd-formula/-/pipelines/385268560

If it's this simple, then we'll only need an additional pillar file for the platforms where this is failing otherwise.

**Comment by aboe76** [comment]
It's that simple look in the osfinger for Debian bullseye for the hint


Op vr 8 okt. 2021 21:57 schreef Imran Iqbal ***@***.***>:

**Comment by myii** [comment]
> @aboe76 OK, as an initial test, running with `networkd.wait_online: false` on all `master` instances:
> 
>     * https://gitlab.com/myii/systemd-formula/-/pipelines/385268560
> 
> 
> If it's this simple, then we'll only need an additional pillar file for the platforms where this is failing otherwise.

OK, that result looks worse than it is because I didn't disable the InSpec verification for `systemd-networkd-wait-online`.  But even looking at the remaining instances which have failed, it looks like it will be relatively easy to resolve nearly all of them.  I don't have time right now but I'll try to look into this soon and get this all finalised.  Thanks for the suggestion, @aboe76.

**Pull request merged**
